apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "new-2048"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aeonzh/argocd-lab.git
    targetRevision: HEAD
    path: app
  destination:
    server: https://kubernetes.default.svc
    namespace: "new-2048"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamesapce=true
