apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: 2048-fullstack
  namespace: default
  labels:
    app: "2048"
spec:
  selector:
    matchLabels:
      app: "2048"
  replicas: 1
  strategy:
    type: "RollingUpdate"
  template:
    metadata:
      labels:
        app: "2048"
    spec:
      containers:
        - name: "2048"
          image: "alexwhen/docker-2048:latest"
